
language: cpp

before_install:
  - git submodule update --init --recursive

before_script:
  - export CXX=${COMPILER}
  - cd ${TRAVIS_BUILD_DIR}
  - cmake -H. -BBuild-Debug -DCMAKE_BUILD_TYPE=Debug -Wdev

script:
  - cd Build-Debug
  - make -j 2

