
language: cpp

matrix:
  include:
    - os: osx
      compiler: clang

addons:
  apt:
    sources:
      - kalakris-cmake
  packages:
    - cmake
    - lcov

before_install:
  - git submodule update --init --recursive
  - |
    if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      brew upgrade cmake
    fi

before_script:
  - export CXX=${COMPILER}
  - cd ${TRAVIS_BUILD_DIR}
  - cmake -H. -BBuild-Debug -DCMAKE_BUILD_TYPE=Debug -Wdev -DENABLE_COVERAGE=On

script:
  - cd Build-Debug
  - make -j 2
  - make test
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]] && [[ "${COMPILER}" == "g++" ]]; then
      make gcov
      make lcov
      bash <(curl -s https://codecov.io/bash) -X gcov || echo "Codecov did not collect coverage reports"
    fi

