version: '{build}'


install:
  - cmmd: echo "Downloading conan..."
  - cmmd: set PATH=%PATH%;%PYTHON%/Scripts/
  - cmmd: pip.exe install conan
  - cmmd: conan user # Create the conan data directory
  - cmmd: conan --version


image: Visual Studio 2017

environment:
  matrix:
    - GENERATOR: "Visual Studio 14"
      CONFIG: Debug

    - GENERATOR: "Visual Studio 15 Win64"
      CONFIG: Release

build_script:
  - cmmd: mkdir build
  - cmmd: conan install . -o gtest:shared=True
  - cmmd: cd build
  - cmmd: cmake ../ -DBUILD_TEST=TRUE
  - cmmd: cmake --build . --config Debug

test_script:
  - cmmd: cd build
  - cmmd: cmake test

