version: '{build}'


install:
  - echo "Downloading conan..."
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe install conan
  - conan user # Create the conan data directory
  - conan --version


image: Visual Studio 2017

environment:
  matrix:
    - GENERATOR: "Visual Studio 14"
      CONFIG: Debug

    - GENERATOR: "Visual Studio 15 Win64"
      CONFIG: Release

build_script:
  - mkdir build
  - cd build
  - conan install ..
  - cd ..
  - cmake -H. -Bbuild -DCMAKE_BUILD_TYPE=Debug -Wdev -DENABLE_COVERAGE=Off
  - cd build
  - cmake --build .

test_script:
  - cd tests\bin
  - 010-TestCase.exe

